# Generated by Django 2.2.7 on 2019-12-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chairman',
            old_name='ChairmanId',
            new_name='chairmanId',
        ),
    ]
