# Generated by Django 2.2.7 on 2019-12-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chairman', '0001_initial'),
        ('uno', '0001_initial'),
        ('calc', '0003_auto_20191127_1629'),
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignComplainUno',
            fields=[
                ('complainId', models.AutoField(primary_key=True, serialize=False)),
                ('setmeetingdate', models.CharField(max_length=25, null=True)),
                ('setmeetingtime', models.CharField(max_length=25, null=True)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Complain')),
                ('uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uno.Uno')),
            ],
        ),
        migrations.CreateModel(
            name='AssignComplainPolice',
            fields=[
                ('complainId', models.AutoField(primary_key=True, serialize=False)),
                ('setmeetingdate', models.CharField(max_length=25, null=True)),
                ('setmeetingtime', models.CharField(max_length=25, null=True)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Complain')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police.Police')),
            ],
        ),
        migrations.CreateModel(
            name='AssignComplainChairman',
            fields=[
                ('complainId', models.AutoField(primary_key=True, serialize=False)),
                ('setmeetingdate', models.CharField(max_length=25, null=True)),
                ('setmeetingtime', models.CharField(max_length=25, null=True)),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.Chairman')),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Complain')),
            ],
        ),
    ]
