# Generated by Django 2.2.7 on 2019-12-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigncomplain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigncomplainchairman',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='assigncomplainpolice',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='assigncomplainuno',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
