# Generated by Django 2.2.7 on 2019-12-04 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assigncomplain', '0002_auto_20191202_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigncomplainchairman',
            name='chairman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairman.Chairman', to_field='ChairmanId'),
        ),
        migrations.AlterField(
            model_name='assigncomplainuno',
            name='uno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uno.Uno', to_field='UnoId'),
        ),
    ]
