# Generated by Django 2.2.7 on 2019-11-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='gp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calc.Generalpeople'),
        ),
    ]
