# Generated by Django 2.2.7 on 2019-11-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_complain_gp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='gp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Generalpeople'),
        ),
    ]
