# Generated by Django 2.2.7 on 2019-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_checkbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkbox',
        ),
        migrations.AddField(
            model_name='complain',
            name='assignCom',
            field=models.BooleanField(default=True),
        ),
    ]
