# Generated by Django 2.2.7 on 2019-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20191203_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='assignCom',
            field=models.BooleanField(default=False),
        ),
    ]
