# Generated by Django 2.2.7 on 2019-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20191205_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='district',
        ),
        migrations.AddField(
            model_name='generalpeople',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
