# Generated by Django 2.2.7 on 2019-12-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uno',
            old_name='UnoId',
            new_name='unoId',
        ),
    ]
